name: apktool
version: 2.1.1
summary: A tool for reverse engineering 3rd party, closed, binary Android apps.
description: A tool for reverse engineering 3rd party, closed, binary Android apps. It can decode resources to nearly original form and rebuild them after making some modifications; it makes possible to debug smali code step by step. Also it makes working with an app easier because of project-like file structure and automation of some repetitive tasks like building apk, etc.

apps:
  apktool:
    command: bin/apktool

parts:
  jdk:
    plugin: copy
    files:
      jre1.8.0_91/*: ./
  apktool:
    plugin: copy
    files:
     apktool: bin/apktool
     apktool.jar: jar/apktool.jar
